# Generated by Django 4.1.6 on 2023-02-23 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='year',
        ),
        migrations.AddField(
            model_name='movie',
            name='img',
            field=models.ImageField(default='ddffs', upload_to='gallery'),
            preserve_default=False,
        ),
    ]
