# Generated by Django 4.1.6 on 2023-02-23 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0002_remove_movie_year_movie_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='year',
            field=models.IntegerField(default=1234),
            preserve_default=False,
        ),
    ]
