# Generated by Django 4.1.6 on 2023-02-23 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0003_movie_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='img',
        ),
    ]
