# Generated by Django 4.1.6 on 2023-02-23 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0004_remove_movie_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='year',
        ),
    ]
